### ISSUE TITLE
Additional text coming up

### ISSUE THREAD

**Issue by Ralph009** [Orange-OpenSource/SoftwareLifecycleEnvImpact#5]
Additional text is coming up under every element of the stages.

![image](https://github.com/Orange-OpenSource/SoftwareLifecycleEnvImpact/assets/41083836/c2b8d3bc-950f-43e1-a43f-92cb3eae73a7)

**Comment by PierreRustOrange** [comment]
Hi,

thank you for reporting this issue, this looks as a side affect of the addition of the licence to every file :/

We'll look into that rapidly !
